# Generated by Django 5.0.3 on 2024-03-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_admin_id_alter_agent_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.agent')),
                ('agent_photo', models.FileField(upload_to='documents/')),
                ('aadhar', models.FileField(upload_to='documents/')),
                ('pancard', models.FileField(upload_to='documents/')),
                ('gst_certificate', models.FileField(upload_to='documents/')),
                ('liscence', models.FileField(upload_to='documents/')),
            ],
            bases=('admin_panel.agent',),
        ),
    ]
