# Generated by Django 5.0.1 on 2024-03-27 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_admin_id_alter_agent_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.TextField(default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.agent')),
                ('agent_photo', models.FileField(upload_to='documents/')),
                ('aadhar', models.FileField(upload_to='documents/')),
                ('pancard', models.FileField(upload_to='documents/')),
                ('gst_certificate', models.FileField(upload_to='documents/')),
                ('liscence', models.FileField(upload_to='documents/')),
            ],
            bases=('admin_panel.agent',),
        ),
        migrations.CreateModel(
            name='bank_accound_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_holder_name', models.CharField(max_length=50, null=True)),
                ('acc_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_num', models.CharField(max_length=100, null=True)),
                ('com_address', models.TextField(default='', null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('company_gst', models.FileField(null=True, upload_to='com_docs/')),
                ('incorporation_certificate', models.FileField(null=True, upload_to='com_docs/')),
                ('article_of_association', models.FileField(null=True, upload_to='com_docs/')),
                ('company_pancard', models.FileField(null=True, upload_to='com_docs/')),
                ('agents', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='admin_panel.agent')),
            ],
        ),
        migrations.CreateModel(
            name='com_directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=256)),
                ('director_postion', models.CharField(blank=True, max_length=256)),
                ('director_email', models.EmailField(max_length=254)),
                ('director_phone_number', models.CharField(max_length=14)),
                ('director_img', models.ImageField(upload_to='com_dir/')),
                ('director_adhar', models.ImageField(upload_to='com_dir/')),
                ('director_pancard', models.FileField(upload_to='com_dir/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_dir', to='admin_panel.company_details')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_photo', models.ImageField(upload_to='individual_photos/')),
                ('aadhar', models.ImageField(upload_to='individual_documents/')),
                ('pancard', models.ImageField(upload_to='individual_documents/')),
                ('gst_certificate', models.ImageField(upload_to='individual_documents/')),
                ('license', models.ImageField(upload_to='individual_documents/')),
                ('individual_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individualssss', to='admin_panel.agent')),
            ],
        ),
    ]
