# Generated by Django 5.0.3 on 2024-03-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.agent')),
                ('company_gst', models.FileField(upload_to='documents/')),
                ('incorporation_certificate', models.FileField(upload_to='documents/')),
                ('article_of_association', models.FileField(upload_to='documents/')),
                ('company_pancard', models.FileField(upload_to='documents/')),
            ],
            bases=('admin_panel.agent',),
        ),
    ]
