# Generated by Django 5.0 on 2023-12-19 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='crnc',
            fields=[
                ('crid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Id')),
                ('crname', models.CharField(max_length=100, verbose_name='Name')),
                ('crsymbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('crdescription', models.TextField(verbose_name='Description')),
                ('crstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='cntry',
            fields=[
                ('cnid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Id')),
                ('cnname', models.CharField(max_length=100, verbose_name='Name')),
                ('cndescription', models.TextField(verbose_name='Description')),
                ('cnstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cncrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.crnc', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='ctgry',
            fields=[
                ('ctid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Id')),
                ('ctname', models.CharField(max_length=50, verbose_name='Name')),
                ('ctcode', models.CharField(max_length=50, verbose_name='Code')),
                ('ctdescription', models.TextField(verbose_name='Description')),
                ('ctimg', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('ctstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='formt',
            fields=[
                ('frid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Id')),
                ('frname', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('frdescription', models.CharField(max_length=255, verbose_name='Description')),
                ('frfltr', models.CharField(max_length=255, verbose_name='Format Filter')),
                ('frstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'File Format Details',
            },
        ),
        migrations.CreateModel(
            name='txmst',
            fields=[
                ('txid', models.AutoField(db_column='txid', primary_key=True, serialize=False, verbose_name='Tax Id')),
                ('txname', models.CharField(max_length=255, unique=True, verbose_name='Tax Name')),
                ('txdescription', models.CharField(max_length=255, verbose_name='Tax Description')),
                ('txisgst', models.BooleanField(default=True, verbose_name='GST')),
                ('txstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Tax Master',
            },
        ),
        migrations.CreateModel(
            name='txdet',
            fields=[
                ('tdid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Tax Detais Id')),
                ('tdname', models.CharField(max_length=255, verbose_name='Tax Details Name')),
                ('tddescription', models.CharField(max_length=255, verbose_name='Tax Details Description')),
                ('tdcgst', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CGST Rate')),
                ('tdsgst', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SGST Rate')),
                ('tdigst', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IGST Rate')),
                ('tdvat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='VAT Rate')),
                ('tdcess', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CESS Rate')),
                ('tdstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tdtxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.txmst', verbose_name='Tax Id')),
            ],
            options={
                'verbose_name': 'Tax Details',
            },
        ),
        migrations.CreateModel(
            name='srvc',
            fields=[
                ('svid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Tax Detais Id')),
                ('svcode', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('svname', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('svdescription', models.CharField(max_length=255, verbose_name='Description')),
                ('svrate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('svratesplit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Split Up')),
                ('svsrvchg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service chg')),
                ('discrt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Rate')),
                ('discamt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amt')),
                ('disctxt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Text')),
                ('svagamt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agent Amt')),
                ('svagrt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agent Rate')),
                ('svtxrt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Rate')),
                ('svtxamt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amt')),
                ('svnetamt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Amt')),
                ('svstatus', models.BooleanField(default=True, verbose_name='Status')),
                ('dtupdatd', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('svcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.ctgry', verbose_name='Category')),
                ('svcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cntry', verbose_name='Country')),
                ('usrid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('svtxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.txmst', verbose_name='Tax')),
            ],
            options={
                'verbose_name': 'Services',
            },
        ),
        migrations.AddField(
            model_name='cntry',
            name='cntxid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.txmst', verbose_name='Tax'),
        ),
    ]
