# Generated by Django 5.0 on 2023-12-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cntry',
            table='cntry',
        ),
        migrations.AlterModelTable(
            name='crnc',
            table='crnc',
        ),
        migrations.AlterModelTable(
            name='ctgry',
            table='ctgry',
        ),
        migrations.AlterModelTable(
            name='formt',
            table='formt',
        ),
        migrations.AlterModelTable(
            name='srvc',
            table='srvc',
        ),
        migrations.AlterModelTable(
            name='txdet',
            table='txdet',
        ),
        migrations.AlterModelTable(
            name='txmst',
            table='txmst',
        ),
    ]
