# Generated by Django 5.0 on 2023-12-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_cntry_table_alter_crnc_table_alter_ctgry_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cntry',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='crnc',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='ctgry',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='formt',
            options={'verbose_name': 'File Format Details', 'verbose_name_plural': 'File Format Details'},
        ),
        migrations.AlterModelOptions(
            name='srvc',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='txdet',
            options={'verbose_name': 'Tax Details', 'verbose_name_plural': 'Tax Details'},
        ),
        migrations.AlterModelOptions(
            name='txmst',
            options={'verbose_name': 'Tax Master', 'verbose_name_plural': 'Tax Master'},
        ),
    ]
