# Generated by Django 5.0 on 2023-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_cntry_options_alter_crnc_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgry',
            name='ctimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
