# Generated by Django 5.0 on 2023-12-29 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_ctgry_ctimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgry',
            name='ctimg',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='DocumentsRequired',
            fields=[
                ('tdid', models.AutoField(db_column='tdid', primary_key=True, serialize=False, verbose_name='Tax Detais Id')),
                ('DocumentName', models.CharField(max_length=50, verbose_name='Document Name')),
                ('Description', models.TextField()),
                ('MaxFileSize', models.IntegerField(verbose_name='Max File Size')),
                ('Status', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('CreatedBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('Format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.formt')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.srvc')),
            ],
        ),
    ]
