# Generated by Django 5.0.1 on 2024-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taken_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Taken'),
        ),
    ]
