# Generated by Django 5.0.1 on 2024-01-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_admcat_srvc_svdoccolltime_srvc_svproctime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crnc',
            name='crstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
    ]
