# Generated by Django 5.0.1 on 2024-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_crnc_crstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admcat',
            name='acstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='admroles',
            name='arstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='clnt',
            name='clstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='clsubsdet',
            name='csstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cntry',
            name='cnstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ctgry',
            name='ctstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentsrequired',
            name='Status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='formt',
            name='frstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='srvc',
            name='svstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='states',
            name='cnstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='txdet',
            name='tdstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='txmst',
            name='txstatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
    ]
