# Generated by Django 5.0.1 on 2024-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_admcat_acstatus_alter_admroles_arstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='stname',
            field=models.CharField(max_length=255, unique=True, verbose_name='State/Province Name'),
        ),
    ]
