# Generated by Django 5.0.1 on 2024-02-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_admcat_usrid_alter_admroles_usrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crnc',
            name='usrid',
            field=models.CharField(max_length=10, verbose_name='Created By'),
        ),
    ]
