# Generated by Django 5.0.1 on 2024-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_crnc_usrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admcat',
            name='usrid',
            field=models.CharField(default=None, editable=False, max_length=10, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admroles',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='clnt',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='clsubsdet',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cntry',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='crnc',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='ctgry',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='formt',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='srvc',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='states',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='txdet',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='txmst',
            name='usrid',
            field=models.CharField(editable=False, max_length=10, verbose_name='Created By'),
        ),
    ]
