# Generated by Django 5.0.1 on 2024-02-21 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_remove_admroles_aracid_remove_admroles_usrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgry',
            name='usrid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
