# Generated by Django 5.0.1 on 2024-02-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_agent_admin_alter_clnt_usrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crnc',
            name='usrid',
            field=models.ForeignKey(db_column='usrid_id', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.customuser', verbose_name='Created By'),
        ),
    ]
