# Generated by Django 5.0.1 on 2024-02-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_crnc_usrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crnc',
            name='usrid',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.customuser', verbose_name='Created By'),
        ),
    ]
