# Generated by Django 3.1.1 on 2024-02-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20240228_1530'),
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_consult_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_notification',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_panel.srvc'),
        ),
        migrations.AlterField(
            model_name='user_service_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
