# Generated by Django 5.0.1 on 2024-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_user_service_details_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service_details',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=255, verbose_name='Status'),
        ),
    ]
