# Generated by Django 5.0.1 on 2024-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_alter_user_service_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service_details',
            name='call_back_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_service_details',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
