# Generated by Django 5.0.3 on 2024-03-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_user_service_details_agent_id'),
        ('user_portal', '0006_user_service_details_call_back_request_and_more'),
    ]

    operations = [
    ]
