# Generated by Django 5.0.3 on 2024-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0007_merge_20240305_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
