# Generated by Django 5.0.3 on 2024-03-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0008_user_notification_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='sender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
