# Generated by Django 5.0.3 on 2024-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0009_user_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service_details',
            name='call_back_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_details',
            name='msg',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
