# Generated by Django 5.0.1 on 2024-03-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0013_remove_user_service_details_taken_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service_details',
            old_name='taken_bys',
            new_name='taken_by',
        ),
    ]
