# Generated by Django 5.0.1 on 2024-03-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0015_alter_user_service_details_taken_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_service_details',
        ),
    ]
