# Generated by Django 5.0.1 on 2024-03-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_admin_id_alter_agent_id_alter_customuser_id_and_more'),
        ('user_portal', '0016_delete_user_service_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_service_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.BooleanField(blank=True, default=False, verbose_name='Payment')),
                ('msg', models.TextField(blank=True, verbose_name='Remarks')),
                ('documents', models.JSONField(blank=True, default='', verbose_name='Documents')),
                ('status', models.CharField(blank=True, default=0, max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('call_back_request', models.IntegerField(default=0)),
                ('agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to=settings.AUTH_USER_MODEL, verbose_name='agent_id')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.srvc', verbose_name='Service')),
                ('taken_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.staff', verbose_name='Takens')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
    ]
