# Generated by Django 5.0 on 2024-01-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_consult_detail',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='free_consult_detail',
            name='service',
            field=models.CharField(blank=True, max_length=15, verbose_name='Service'),
        ),
    ]
