# Generated by Django 5.0 on 2024-02-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_states_stname'),
        ('user_portal', '0002_alter_free_consult_detail_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('payment', models.BooleanField(default=False, verbose_name='Payment')),
                ('time', models.TimeField(verbose_name='Shedule time')),
                ('date', models.DateField(verbose_name='Shedule date')),
                ('msg', models.TextField(verbose_name='user Query')),
                ('taken_by', models.CharField(blank=True, max_length=255, verbose_name='Taken')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.srvc', verbose_name='Service')),
            ],
        ),
    ]
