# Generated by Django 5.0.1 on 2024-02-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification',
            new_name='user_notification',
        ),
    ]
