# Generated by Django 5.0 on 2024-02-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='time',
        ),
    ]
