# Generated by Django 5.0.1 on 2024-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_rename_notification_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification',
            name='recepient',
            field=models.TextField(),
        ),
    ]
