# Generated by Django 5.0.1 on 2024-02-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_alter_user_notification_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification',
            name='recepient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.userdata'),
        ),
    ]
