# Generated by Django 5.0 on 2024-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_remove_userdata_date_remove_userdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='documents',
            field=models.JSONField(blank=True, default='', verbose_name='Documents'),
        ),
    ]
