# Generated by Django 5.0 on 2024-02-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_states_stname'),
        ('user_portal', '0005_userdata_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='taken_by',
        ),
        migrations.CreateModel(
            name='user_service_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.BooleanField(default=False, verbose_name='Payment')),
                ('msg', models.TextField(verbose_name='user Query')),
                ('documents', models.JSONField(blank=True, default='', verbose_name='Documents')),
                ('taken_by', models.CharField(blank=True, max_length=255, verbose_name='Taken')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.srvc', verbose_name='Service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.userdata', verbose_name='user_id')),
            ],
        ),
    ]
