# Generated by Django 5.0.1 on 2024-02-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_alter_user_notification_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_portal.user_service_details'),
        ),
    ]
