# Generated by Django 5.0.1 on 2024-02-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_alter_user_service_details_user_id'),
        ('user_portal', '0006_user_notification_service'),
    ]

    operations = [
    ]
