# Generated by Django 5.0.1 on 2024-02-20 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0007_merge_20240219_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.userdata', verbose_name='user_id'),
        ),
    ]
